main: club.mher.compass.Compass
name: BedWars2023-Compass
author: NemTheKoshka, Mher Zaqaryan
version: ${project.version}
api-version: '1.0'
description: BedWars2023 Compass Addon By NemTheKoshka forked from Mher Zaqaryan

softdepend:
  - BedWars2023
  - PlaceholderAPI
  - Vault